# ThoughtLink - Docker image for NVIDIA GPUs (Ampere / Ada / Hopper / Blackwell)
# CUDA 12.8 + Python 3.12 + PyTorch (cu128 multi-arch wheels) with GPU support
#
# Architecture-resilient: the cu128 torch wheels ship compiled kernels for
# sm_80..sm_120 plus PTX, and the NVIDIA Container Toolkit injects the host
# driver at run time, so one image runs on RTX 30xx/40xx/50xx and datacenter
# GPUs alike — no per-GPU rebuild needed.
#
# Build:   docker build -t thoughtlink .
# Run:     docker run --gpus all -it thoughtlink
# Jupyter: docker compose up jupyter

FROM nvidia/cuda:12.8.1-devel-ubuntu22.04 AS base

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    MUJOCO_GL=egl \
    PYOPENGL_PLATFORM=egl \
    UV_LINK_MODE=copy \
    NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics

# System dependencies (single layer)
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y --no-install-recommends \
    python3.12 \
    python3.12-venv \
    python3.12-dev \
    git \
    curl \
    # MuJoCo / OpenGL headless rendering
    libgl1-mesa-glx \
    libgl1-mesa-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libglfw3 \
    libglfw3-dev \
    libosmesa6-dev \
    patchelf \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install UV (pinned version for reproducibility; must understand the cu128
# index + sources in pyproject.toml and read the uv.lock generated by uv 0.11)
COPY --from=ghcr.io/astral-sh/uv:0.11 /uv /uvx /bin/

WORKDIR /app

# Dependency install layer (cached unless pyproject.toml/uv.lock change)
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --python 3.12

# Project source
COPY src/ src/
COPY configs/ configs/
COPY scripts/ scripts/
COPY tests/ tests/
COPY notebooks/ notebooks/
COPY docs/ docs/

# Healthcheck: verify Python + thoughtlink importable
HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
    CMD uv run python -c "import thoughtlink" || exit 1

CMD ["uv", "run", "python", "-c", "import thoughtlink; print(f'ThoughtLink v{thoughtlink.__version__} ready')"]

# --- Jupyter stage ---
FROM base AS jupyter
EXPOSE 8888
CMD ["uv", "run", "jupyter", "notebook", \
     "--ip=0.0.0.0", "--port=8888", "--no-browser", \
     "--allow-root", "--NotebookApp.token=''"]

# --- Streamlit stage ---
FROM base AS streamlit
EXPOSE 8501
CMD ["uv", "run", "streamlit", "run", \
     "src/thoughtlink/viz/dashboard.py", \
     "--server.address=0.0.0.0", "--server.port=8501"]
